name = "Doppelkeks"
uuid = "4e4077ad-e7c8-45c8-9812-3f131d6fcb52"
authors = ["Sukera <Seelengrab@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
